- name: Application configuration
  hosts: ve_bigips
  connection: local
  gather_facts: false

  tasks:

  - name: Setting up provider values
    set_fact:
     provider:
      server: "{{inventory_hostname}}"
      server_port: "443"
      validate_certs: "False"

  - name: Create nodes
    bigip_node:
      provider: "{{provider}}"
      host: "{{hostvars[item].inventory_hostname}}"
      name: "{{hostvars[item].inventory_hostname}}"
      monitors:
      - icmp
      monitor_type: "single"

    loop: "{{ groups['webservers'] }}"

  - name: Create pool
    bigip_pool:
      provider: "{{provider}}"
      name: "{{pool_name}}"
      lb_method: "round-robin"
      monitors: "/Common/http"
      monitor_type: "and_list"

  - name: Add Pool members
    bigip_pool_member:
      provider: "{{provider}}"
      state: "present"
      name: "{{hostvars[item].inventory_hostname}}"
      host: "{{hostvars[item].inventory_hostname}}"
      port: "80"
      pool: "{{pool_name}}"
    loop: "{{ groups['webservers'] }}"

  - name: Add Virtual Server
    bigip_virtual_server:
      provider: "{{provider}}"
      name: "{{vip_name}}"
      destination: "{{vip_ip}}"
      port: "443"
      profiles:
      - http
      - clientssl
      pool: "{{pool_name}}"
      snat: "automap"
  
   - name: Create a redirect virtual serbver
     bigip_virtual_server:
      provider: "{{provider}}"
      description: "Redirect Virtual server"
      name: "{{vip_name}}_redirect"
      destination: "{{vip_ip}}"
      port: 80
      profiles:
      - http
      all_rules:
      - _sys_https_redirect
